# 📤💎⚡ LEGENDARY PROMTAIL CONFIGURATION ⚡💎📤
# Advanced log collection for HYPERFOCUS Zone Empire
# Automatically discovers and ships logs from all containers and services

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://legendary-loki:3100/loki/api/v1/push

scrape_configs:
  # 🐳 DOCKER CONTAINER LOGS
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log

    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs:
      - json:
          expressions:
            tag:
          source: attrs
      - regex:
          expression: (?P<container_name>(?:[^|]*))/(?P<container_id>(?:[^|]*))
          source: tag
      - timestamp:
          format: RFC3339Nano
          source: time
      - labels:
          stream:
          container_name:
          container_id:
      - output:
          source: output

  # 📊 LEGENDARY HEALTH SERVICE LOGS
  - job_name: legendary-health-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: legendary-health
          service: health-service
          __path__: /app/logs/legendary_health_*.log

    pipeline_stages:
      - regex:
          expression: '(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}) - (?P<level>\w+) - (?P<message>.*)'
      - timestamp:
          format: '2006-01-02 15:04:05,000'
          source: timestamp
      - labels:
          level:
      - output:
          source: message

  # 🧠 MEMORY CRYSTAL SERVICE LOGS
  - job_name: memory-crystal-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: memory-crystal
          service: memory-crystal-service
          __path__: /app/logs/memory_crystal_*.log

    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            crystal_id: crystal_id
            broskie_rewards: broskie_rewards
      - timestamp:
          format: RFC3339
          source: timestamp
      - labels:
          level:
          crystal_id:
      - output:
          source: message

  # 🎯 PROMETHEUS LOGS
  - job_name: prometheus-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: prometheus
          service: prometheus
          __path__: /prometheus/prometheus.log

  # 📊 GRAFANA LOGS
  - job_name: grafana-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: grafana
          service: grafana
          __path__: /var/lib/grafana/grafana.log

  # 🔔 ALERTMANAGER LOGS
  - job_name: alertmanager-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: alertmanager
          service: alertmanager
          __path__: /alertmanager/alertmanager.log

  # 📝 SYSTEM LOGS (if available)
  - job_name: system-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/*.log

    pipeline_stages:
      - regex:
          expression: '(?P<timestamp>\w{3} \d{2} \d{2}:\d{2}:\d{2}) (?P<hostname>\w+) (?P<service>\w+): (?P<message>.*)'
      - timestamp:
          format: Jan 02 15:04:05
          source: timestamp
      - labels:
          hostname:
          service:
      - output:
          source: message

  # 🚀 APPLICATION LOGS (Generic catch-all)
  - job_name: application-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: applications
          __path__: /app/logs/*.log

    pipeline_stages:
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2}'
          max_wait_time: 3s
      - regex:
          expression: '(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) \[(?P<level>\w+)\] (?P<component>\w+): (?P<message>.*)'
      - timestamp:
          format: '2006-01-02 15:04:05'
          source: timestamp
      - labels:
          level:
          component:
      - output:
          source: message
