services:
  grafana:
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 1G
    image: grafana/grafana:latest
    ports:
    - 3000-3002:3000
  load_balancer:
    image: nginx:alpine
    ports:
    - 80:80
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
  prometheus:
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '1'
          memory: 2G
    image: prom/prometheus:latest
    ports:
    - 9090-9091:9090
version: '3.8'
