# 📊💎⚡ LEGENDARY GRAFANA DATASOURCE PROVISIONING ⚡💎📊
# Auto-provisioned data sources for comprehensive monitoring
# ADHD-optimized configuration with intelligent defaults

apiVersion: 1

datasources:
# 📊 PRIMARY PROMETHEUS DATA SOURCE
- name: 'Legendary Prometheus'
  type: prometheus
  access: proxy
  orgId: 1
  uid: 'legendary-prometheus'
  url: http://prometheus:9090
  isDefault: true
  version: 1
  editable: true
  jsonData:
    httpMethod: POST
    manageAlerts: true
    prometheusType: Prometheus
    prometheusVersion: 2.45.0
    cacheLevel: 'High'
    disableMetricsLookup: false
    customQueryParameters: ''
    exemplarTraceIdDestinations:
      - name: trace_id
        datasourceUid: 'legendary-tempo'
        urlDisplayLabel: 'View Trace'
    # 🎯 ADHD-OPTIMIZED: Longer timeouts for complex queries
    timeInterval: '15s'
    queryTimeout: '120s'

# 📝 PRIMARY LOKI LOG AGGREGATION
- name: 'Legendary Loki'
  type: loki
  access: proxy
  orgId: 1
  uid: 'legendary-loki'
  url: http://loki:3100
  version: 1
  editable: true
  jsonData:
    maxLines: 1000
    # 🎯 ADHD-FRIENDLY: Derived fields for easy navigation
    derivedFields:
      - name: 'TraceID'
        matcherRegex: 'trace_id=(\w+)'
        url: '$${__value.raw}'
        datasourceUid: 'legendary-tempo'
        urlDisplayLabel: 'Trace: $${__value.raw}'
      - name: 'HealthScore'
        matcherRegex: 'health_score=(\d+\.?\d*)'
        url: ''
        urlDisplayLabel: 'Health: $${__value.raw}%'

# 🔍 JAEGER TRACING SYSTEM
- name: 'Legendary Jaeger'
  type: jaeger
  access: proxy
  orgId: 1
  uid: 'legendary-jaeger'
  url: http://jaeger-query:16686
  version: 1
  editable: true
  jsonData:
    tracesToLogsV2:
      datasourceUid: 'legendary-loki'
      spanStartTimeShift: '-1h'
      spanEndTimeShift: '1h'
      tags: ['job', 'instance', 'pod', 'namespace']
      filterByTraceID: true
      filterBySpanID: false
      customQuery: true
      query: '{job="$${__tags.job}"} |~ "$${__span.traceId}"'
    tracesToMetrics:
      datasourceUid: 'legendary-prometheus'
      tags: [{ key: 'service.name', value: 'service' }, { key: 'job' }]
      queries:
        - name: 'Sample query'
          query: 'sum(rate(traces_spanmetrics_latency_bucket{$$__tags}[5m]))'
    nodeGraph:
      enabled: true

# ⚡ TEMPO DISTRIBUTED TRACING
- name: 'Legendary Tempo'
  type: tempo
  access: proxy
  orgId: 1
  uid: 'legendary-tempo'
  url: http://tempo:3200
  version: 1
  editable: true
  jsonData:
    httpMethod: GET
    tracesToLogsV2:
      datasourceUid: 'legendary-loki'
      spanStartTimeShift: '-1h'
      spanEndTimeShift: '1h'
      tags: ['job', 'instance']
      filterByTraceID: true
      customQuery: true
      query: '{job="$${__tags.job}"} |~ "$${__span.traceId}"'
    tracesToMetrics:
      datasourceUid: 'legendary-prometheus'
      tags: [{ key: 'service.name', value: 'service' }]
      queries:
        - name: 'Request rate'
          query: 'sum(rate(tempo_request_duration_seconds_count{$$__tags}[5m]))'
        - name: 'Request duration'
          query: 'histogram_quantile(0.9, sum(rate(tempo_request_duration_seconds_bucket{$$__tags}[5m])) by (le))'
    nodeGraph:
      enabled: true
    search:
      hide: false
    lokiSearch:
      datasourceUid: 'legendary-loki'

# 🗄️ REDIS MEMORY CRYSTAL CACHE
- name: 'Memory Crystal Redis'
  type: redis-datasource
  access: proxy
  orgId: 1
  uid: 'legendary-redis'
  url: redis://redis:6379
  version: 1
  editable: true
  jsonData:
    client: 'standalone'
    poolSize: 5
    timeout: 10
    pingInterval: 0
    pipelineWindow: 0

# 📈 ALERTMANAGER INTEGRATION
- name: 'Legendary Alertmanager'
  type: alertmanager
  access: proxy
  orgId: 1
  uid: 'legendary-alertmanager'
  url: http://alertmanager:9093
  version: 1
  editable: true
  jsonData:
    implementation: prometheus
